### ISSUE TITLE
Ruffus installation error (ModuleNotFoundError: No module named 'task')

### ISSUE THREAD

**Issue by Aditya-Gautam20** [cgat-developers/ruffus#128]
Hello ,
I was able to install version 2.8.4 ,but I am trying to install Ruffus 2.4.1 , which is a mandatory version in Kronos_pipeline , i get this error , task not found , i see the that task.py is present and the functions  to be imported are all present  , can someone help with this .Below is the full error.

/ruffus-2.4.1$ pip install ruffus==2.4.1 --upgrade
Collecting ruffus==2.4.1
  Using cached ruffus-2.4.1.tar.gz (92 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vug5vl6o/ruffus_56d1596ba79341fb8c56b74de1d3c109/setup.py", line 12, in <module>
          import ruffus.ruffus_version
        File "/tmp/pip-install-vug5vl6o/ruffus_56d1596ba79341fb8c56b74de1d3c109/ruffus/__init__.py", line 29, in <module>
          from task import pipeline_printout, pipeline_printout_graph, pipeline_run, register_cleanup, check_if_uptodate, active_if, split, transform, merge, collate, files, files_re, follows, parallel, stderr_logger, black_hole_logger, suffix, regex, inputs, add_inputs, touch_file, combine, mkdir, output_from, posttask, JobSignalledBreak, runtime_parameter, jobs_limit, formatter, subdivide, originate
      ModuleNotFoundError: No module named 'task'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by IanSudbery** [comment]
Looks to me like this might be a python version problem. What version of python is installed? I don't remember how old 2.4.1 is, but is it possible that 2.4.1 was python 2.7 only?

**Comment by Aditya-Gautam20** [comment]
Yes that was it , thankyou very much , installed
