### ISSUE TITLE
Install fails on Python 3.7

### ISSUE THREAD

**Issue by jbarlow83** [cgat-developers/ruffus#90]
The issue is:

```
  Downloading https://files.pythonhosted.org/packages/97/fe/12445c6793350ab5dbf76cb87a122b9e9aab9a9040a2801004806d985216/ruffus-2.6.3.tar.gz (36.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yr24g9ol/ruffus/setup.py", line 12, in <module>
        import ruffus.ruffus_version
      File "/tmp/pip-install-yr24g9ol/ruffus/ruffus/__init__.py", line 28, in <module>
        from .task import Pipeline, Task
      File "/tmp/pip-install-yr24g9ol/ruffus/ruffus/task.py", line 715, in <module>
        verbose=0)
    TypeError: namedtuple() got an unexpected keyword argument 'verbose'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yr24g9ol/ruffus/
```

The ``verbose`` argument to `namedtuple()` was removed in Python 3.7.

https://docs.python.org/3/library/collections.html#collections.namedtuple

**Comment by jbarlow83** [comment]
PR'ed it instead: #92
